download_url: https://galaxy.ansible.com/download/ovirt-ovirt-3.1.3.tar.gz
format_version: 1.0.0
name: ovirt
namespace: ovirt
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.1.3
version_url: https://galaxy.ansible.com/api/v2/collections/ovirt/ovirt/versions/3.1.3/
